services:
- type: web
  name: next-js-github
  runtime: node
  plan: starter
  buildCommand: yarn; yarn build
  startCommand: yarn start
  autoDeploy: false
  previews:
    generation: automatic
  envVars:
  - key: NODE_ENV
    value: production
  - key: LIZARD
    value: iguana_not_chicken
# Uncomment the following to deploy this app as a static site on render
# - type: web
#   name: nextjs-static
#   runtime: static
#   buildCommand: yarn; yarn build
#   staticPublishPath: out
#   pullRequestPreviewsEnabled: true     # optional
#   envVars:
#   - key: NODE_ENV
#     value: production

